unbind C-b
set -g prefix 'C-a'

set -g default-shell /usr/bin/zsh

unbind '"'
bind - splitw -v -c '#{pane_current_path}' #垂直方向新增面板，默认进入当前目录
unbind %
bind | splitw -h -c '#{pane_current_path}' # 水平方向新增面板，默认进入当前目

# 绑定hjkl键为面板切换的上下左右键
bind -r k select-pane -U # 绑定k为↑
bind -r j select-pane -D # 绑定j为↓
bind -r h select-pane -L # 绑定h为←
bind -r l select-pane -R # 绑定l为→

#启动鼠标支持
set-option -g mouse on

# 开启vi风格后，支持vi的C-d、C-u、hjkl等快捷键
setw -g mode-keys vi

# 绑定vim模式的复制 
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi V send-keys -X rectangle-toggle

# 设置转义键延时100ms, 默认500, 转义键可能是类似前导键有先后顺序的组合键, 主要是用于让vim的fcitx插件延迟降低
set -sg escape-time 100

# 将配色改为xterm-256color
set -g default-terminal "xterm-256color"

#窗口编号从1开始
set -g base-index 1

#插件列表
set -g @plugin 'tmux-plugins/tpm'
#set -g @plugin 'tmux-plugins/tmux-sensible

# 让tmux、vim使用一致的快捷键切换窗格
set -g @plugin 'christoomey/vim-tmux-navigator'


# tmux剪切板和系统剪切板, x11需要xsel, wayland需要wl-copy
# 实际上安装xclip才可以
set -g @plugin 'tmux-plugins/tmux-yank'

# 下面两个操作是取消鼠标选中即复制的逻辑
unbind -T copy-mode-vi MouseDragEnd1Pane
set -g @yank_with_mouse off

# 现场恢复插件
# prefix + <c-s> :保存现场
# prefix + <c-r> :恢复现场
set -g @plugin 'tmux-plugins/tmux-resurrect'
# 持续保存现场插件
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @resurrect-capture-pane-contents 'on' #恢复窗格

#使用：
# prefix + I 下载
# prefix + U 更新
# prefix + u 卸载注释的或者删除的插件
#运行插件管理器
#插件github地址：tmux-plugins/tpm
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
run -b '~/.tmux/plugins/tpm/tpm'
